@startuml

' style tweaks to make the diagram a little more readable
skinparam {
	Style strictuml
	RoundCorner 8

	Sequence {
		' make activations yellow too
		LifeLineBackgroundColor #FDFDCD

		' make stereotypes less ugly
		Stereotype {
			Font {
				Size 11
				Style plain
			}
		}
	}

	DatabaseBorderColor #A80036

}

title Search By ID

actor User as user
participant "Main" as main << main >>
participant "MainMenu" as menu << frame >>
participant "ProductViewer" as report << dialog >>
participant "ProductDatabaseDAO" as dao << DAO >>
database Database
participant "SimpleListModel\n:model" as model
'participant "ProductEditor" as editor << dialog >>
'participant "ValidationHelper" as validator

create menu
main -> menu : « create »

user -> menu : clicks 'View Products'
activate menu

create report
menu -> report : « create »

activate report
create dao
report -> dao: « create »


note over report: as shown in\n'View Products'\ndiagram
user <-- report : list of products displayed
deactivate report

user -> report++ : enter an ID
report--

user -> report++ : clicks 'Search'
report -> dao++ : getProductById(id)
dao -> Database++ : select * from product\n where Product_ID
return ResultSet
dao->dao: reconstruct product\n from ResultSet
dao --> report: product
dao--

create model
report -> model : « construct »
report -> model++ : updateItems(product)
model--
report -> report : productsList.setModel(model)

note left : product searched now\nvisible to user
@enduml
